name: Send Email

on:
  workflow_dispatch:
  schedule:
    - cron: "* 19 * * *" 

jobs:
  post-to-instagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Instagram Post Script
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
        run: |
          python main.py
